import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import SmoothScroll from "@/components/SmoothScroll";
import Footer from "@/components/Footer";

const poppins = localFont({ src: "../../public/fonts/Poppins-Regular.ttf" });

export const metadata: Metadata = {
  title: "Image Galary - unsplash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.style} bg-neutral-950 text-neutral-50`}>
        <SmoothScroll>
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
